databases:
  - name: rashid
    databaseName: rashid
    user: rashid_user

services:
  - type: web
    name: ROR-Capstone
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rashid
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false